name: mlf-core linting
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:

  mlf-core-lint:
    name: Run mlf-core lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mlf-core
        run: |
          pip install mlf-core

      - name: Run mlf-core lint
        run: |
          mlf-core lint .


  flake8:
    name: Run flake8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flake8
        run: |
            pip install flake8

      - name: Lint with flake8
        run: |
            flake8 .

  bandit:
    name: Run bandit
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: bandit -r {{ cookiecutter.project_slug }} -c .bandit.yml
