name: Build mlf-core Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Build mlf-core
        run: pip install .

      - name: Run mlf-core --help
        run: mlf-core --help

      - name: Install required twine packaging dependencies
        run: pip install setuptools wheel twine

      - name: Build twine package
        run: python setup.py sdist bdist_wheel

      - name: Check twine package
        run: twine check dist/*
