name: Create package-prediction Pytorch Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build mlf-core
        run: |
          make install

      - name: Create package-prediction Pytorch Template
        run: |
          cd ..
          echo -e "\033[B\n\n\n\n\nn\n\n\n\n\nn" | mlf-core create

#      - name: Build package-prediction Pytorch
#        run: |
#          cd ..
#          cd exploding_springfield
#          make install
