name: Create mlflow_pytorch Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build mlf-core
        run: |
          make install

      - name: Create mlflow_pytorch Template
        run: |
          cd ..
          echo -e "\n\n\n\n\n\n\n\n\nn" | mlf-core create
