name: Create mlflow Template

on: [push, pull_request]

jobs:
  create:
    name: Create mlflow-${{ matrix.template }} Template (${{ matrix.container }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        template: [ 'pytorch', 'tensorflow', 'xgboost', 'xgboost_dask' ]
        container: [ 'docker', 'conda' ]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build mlf-core
        run: |
          make install

      - name: Create mlflow-${{ matrix.template }} Template
        run: |
          cd ..
          bash mlf-core/.github/create.sh ${{ matrix.template }}

      # https://github.com/docker/build-push-action/issues/90
      - name: Copy workaround
        run: |
          cp ../exploding_springfield/Dockerfile .
          cp ../exploding_springfield/environment.yml .

      - name: Install flake8
        run: pip install flake8

      - name: Lint project with flake8
        run: flake8 ../exploding_springfield

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: bandit -r ../exploding_springfield -c ../exploding_springfield/.bandit.yml

      - name: Build Docker container
        if: matrix.container == 'docker'
        uses: docker/build-push-action@v1
        with:
          repository: ghcr.io/homergithub/exploding_springfield
          tags: 0.1.0-SNAPSHOT
          push: false

      - name: Setup miniconda
        if: matrix.container == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.container == 'conda'
        run: conda clean -a

      - name: Enable conda and disable docker
        if: matrix.container == 'conda'
        run: |
          sed -i 's/# conda_env/conda_env/' ../exploding_springfield/MLproject
          sed -i '10,13d' ../exploding_springfield/MLproject

      - name: Install mlflow
        run: pip install mlflow

      - name: Train on the CPU
        run: |
          cd ../exploding_springfield
          mlflow run . -P max_epochs=1
